name: News Wire 24 Auto Update
on:
  schedule:
    - cron: '30 2 * * *'
    - cron: '30 6 * * *'
    - cron: '30 9 * * *'
    - cron: '30 15 * * *'
    - cron: '30 18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Fetch News
        run: node fetch.js
        env:
          NEWSDATA_KEY: ${{ secrets.NEWSDATA_KEY }}
      - name: Save News
        run: |
          git config --global user.name "News Wire Bot"
          git config --global user.email "bot@newswire24.com"
          git add news.json
          git commit -m "auto update" || echo "no changes"
          git push
